Repository cse110-sp25-group12/cse110-sp25-group12, pull requests merged in 2025-06, with the labels that each got.

#104 Frontend/card buttons
  source/components/job-card.js
  source/pages/add_application.html
  source/pages/applications.html
Labels: High Priority

#131 modified the controls and empty state dialog
  source/components/applications.css
Labels: High Priority

#128 Backend/add comments application pages
  source/js/add_application.js
  source/js/applications-page.js
Labels: Medium Priority

#137 fixed offset cards when adding
  source/components/applications.css
Labels: bug
